# Azure pipeline to build docker image

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'package'

## Copy build artifact to place where docker can find it      
-  task: Bash@3
   inputs:
      targetType: inline
      script: |
         echo $(ls /home/vsts/work/1/s/)
         #cp build artificat into directory where can be used by Dockerfile
         cp /home/vsts/work/1/s/target/tasking.jar /home/vsts/work/1/s/tasking.jar
         echo $(ls /home/vsts/work/1/s/)
- task: Docker@2
  inputs:
    containerRegistry: 'myRegistry'
    repository: 'tasking'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'